name: Autograde

on:
  push:
    branches:
      - develop
      - 'feature/activity**'
  pull_request:
    branches:
      - develop
      - 'feature/activity**'
                
jobs:
  run-autograde:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v3

    - name: Configurar entorno virtual
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Clonar repositorio de evaluación
      run: git clone https://chucholoport:${{ secrets.AUTOGRADE_PAT }}@github.com/chucholoport/autograde-core.git

    - name: Ejecutar pruebas
      working-directory: autograde-core
      run: |
        pytest REDES-NEURONALES/01_redes_neuronales/test_01_red_neuronal_artificial.py
        pytest REDES-NEURONALES/01_redes_neuronales/test_02_red_pequena.py
        pytest REDES-NEURONALES/01_redes_neuronales/test_hw_redes_neuronales_artificiales.py